name: Tests

on:
  push:
    branches:
      - main
      - "*.x"
  pull_request:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Install Node dependencies
        run: npm install

      - name: Build Tailwind Assets
        run: npm run build

      - name: Copy environment file
        run: cp .env.production .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run Migrations
        run: php artisan migrate --force

      - name: Seed the Database
        run: php artisan db:seed

      - name: Execute tests
        run: vendor/bin/pest
